import { useEffect, useMemo, useState } from 'react'
import './App.css'
import { evaluateEpisode, getProcedureEligibility, type Answer, type EvaluationInput, type Observation } from './domain/evaluate'
import { importEpisodes, listEpisodes, saveEpisode, type SavedEpisode } from './storage/db'
import { parseBackupText } from './storage/backup'

const questions: Array<[keyof EvaluationInput['screen'], string]> = [
  ['neurological', 'Новая слабость/онемение, нарушение речи, двоение или выраженное новое нарушение координации?'],
  ['lossOfConsciousness', 'Была потеря сознания?'], ['severeHeadache', 'Есть внезапная необычно сильная головная боль?'],
  ['neckTraumaPain', 'Есть острая боль в шее после травмы вместе с головокружением?'], ['continuousVertigoAtRest', 'Новое сильное головокружение сохраняется в покое?'], ['suddenHearingLoss', 'Есть внезапное снижение слуха?'],
  ['persistentVomiting', 'Рвота не даёт пить?'], ['downbeatObserved', 'Ранее замечали преимущественно нисходящие движения глаз?'],
  ['movementRestriction', 'Есть ограничение движений шеи/спины, нестабильность или запрет врача на позы?'],
]
const blankScreen = Object.fromEntries(questions.map(([key]) => [key, 'unanswered'])) as Record<keyof EvaluationInput['screen'], Answer>
const emptyInput = (): EvaluationInput => ({ screen: { ...blankScreen, complete: false }, observations: [], preparation: { adult: false, helper: false, safeSurface: false, training: false }, instruction: null })
const id = () => crypto.randomUUID()

function Choice({ value, onChange }: { value: Answer; onChange: (value: Answer) => void }) { return <div className="choices">{(['yes', 'no', 'unknown'] as Answer[]).map(v => <button key={v} type="button" className={value === v ? 'selected' : ''} onClick={() => onChange(v)}>{v === 'yes' ? 'Да' : v === 'no' ? 'Нет' : 'Не знаю'}</button>)}</div> }
function Diagram({ side }: { side: 'right' | 'left' }) { return <figure className="diagram"><svg viewBox="0 0 430 160" role="img" aria-label={`Схема положения для ${side === 'right' ? 'правой' : 'левой'} стороны`}><rect x="38" y="108" width="350" height="24" rx="3" fill="#d8ddd8"/><rect x="125" y="86" width="120" height="22" rx="4" fill="#adc2bf"/><circle cx="245" cy="69" r="24" fill="#f0c8a5"/><path d="M200 91L135 107" stroke="#2d5c56" strokeWidth="15" strokeLinecap="round"/><path d={side === 'right' ? 'M264 65 C300 48 325 62 338 81' : 'M226 65 C190 48 165 62 152 81'} stroke="#cf6f49" strokeWidth="4" fill="none"/><text x="185" y="151" fill="#33413f" fontSize="14">Поворот головы ~45° к проверяемому уху</text></svg><figcaption>Ориентир, а не замена обучению. Голова поддержана помощником.</figcaption></figure> }

const newObservation = (): Observation => ({ test: 'dix_hallpike', side: 'unknown', status: 'partial', vertigo: 'unanswered', eyeVisibility: 'unknown', nystagmus: 'uncertain', vertical: 'unknown', horizontal: 'unknown', torsion: 'unknown', durationSeconds: null })
function ManualObservationForm({ onAdd }: { onAdd: (observation: Observation) => void }) {
  const [draft, setDraft] = useState<Observation>(newObservation)
  const update = (key: keyof Observation, value: Observation[keyof Observation]) => setDraft(current => ({ ...current, [key]: value } as Observation))
  return <form className="observation-form" onSubmit={event => { event.preventDefault(); onAdd(draft); setDraft(newObservation()) }}><h3>Добавить наблюдение</h3><p>Запишите только увиденное. По умолчанию запись отмечена как частичная, пока все детали не подтверждены.</p>
    <label>Проба<select value={draft.test} onChange={event => update('test', event.target.value as Observation['test'])}><option value="dix_hallpike">Дикса–Холлпайка</option><option value="supine_roll">Поворот лёжа (supine roll)</option><option value="other">Другая запись</option></select></label>
    <label>Сторона<select value={draft.side} onChange={event => update('side', event.target.value as Observation['side'])}><option value="unknown">Не знаю</option><option value="right">Правая</option><option value="left">Левая</option></select></label>
    <label>Статус выполнения<select value={draft.status} onChange={event => update('status', event.target.value as Observation['status'])}><option value="partial">Частично</option><option value="completed">Завершена</option><option value="aborted">Прервана</option></select></label>
    <label>Было головокружение?<select value={draft.vertigo} onChange={event => update('vertigo', event.target.value as Answer)}><option value="unanswered">Не отвечено</option><option value="yes">Да</option><option value="no">Нет</option><option value="unknown">Не знаю</option></select></label>
    <label>Видимость глаз<select value={draft.eyeVisibility} onChange={event => update('eyeVisibility', event.target.value as Observation['eyeVisibility'])}><option value="unknown">Не знаю</option><option value="adequate">Достаточная</option><option value="limited">Ограниченная</option><option value="closed">Глаза закрыты</option></select></label>
    <label>Движения глаз<select value={draft.nystagmus} onChange={event => update('nystagmus', event.target.value as Observation['nystagmus'])}><option value="uncertain">Не уверен(а)</option><option value="observed">Наблюдались</option><option value="not_seen">Не увидел(а)</option><option value="not_observed">Не наблюдались</option></select></label>
    <label>Вертикальное направление<select value={draft.vertical} onChange={event => update('vertical', event.target.value as Observation['vertical'])}><option value="unknown">Не знаю</option><option value="up">Вверх</option><option value="down">Вниз</option><option value="none">Нет</option></select></label>
    <label>Горизонтальное направление<select value={draft.horizontal} onChange={event => update('horizontal', event.target.value as Observation['horizontal'])}><option value="unknown">Не знаю</option><option value="patient_right">К правой стороне человека</option><option value="patient_left">К левой стороне человека</option><option value="none">Нет</option></select></label>
    <label>Торсионное направление<select value={draft.torsion} onChange={event => update('torsion', event.target.value as Observation['torsion'])}><option value="unknown">Не знаю</option><option value="patient_right">К правой стороне человека</option><option value="patient_left">К левой стороне человека</option><option value="none">Нет</option></select></label>
    <label>Длительность, секунд (если известна)<input type="number" min="0" value={draft.durationSeconds ?? ''} onChange={event => update('durationSeconds', event.target.value === '' ? null : Number(event.target.value))} /></label>
    <button type="submit">Добавить наблюдение</button></form>
}

export default function App() {
  const [tab, setTab] = useState<'home'|'screen'|'record'|'history'|'help'>('home')
  const [input, setInput] = useState<EvaluationInput>(emptyInput)
  const [saved, setSaved] = useState<SavedEpisode[]>([])
  const [notice, setNotice] = useState('')
  const [consented, setConsented] = useState(localStorage.getItem('bppv-consent') === 'yes')
  const [acknowledged, setAcknowledged] = useState(false)
  useEffect(() => { listEpisodes().then(setSaved).catch(() => setNotice('Не удалось открыть локальное хранилище.')) }, [])
  const assessment = useMemo(() => evaluateEpisode(input), [input])
  const eligibility = useMemo(() => getProcedureEligibility(input, assessment), [input, assessment])
  const setScreen = (key: keyof EvaluationInput['screen'], value: Answer) => setInput(current => ({ ...current, screen: { ...current.screen, [key]: value, complete: questions.every(([q]) => (q === key ? value : current.screen[q]) !== 'unanswered') } }))
  const addObservation = (observation: Observation) => { setInput(current => ({ ...current, observations: [...current.observations, observation] })); setNotice('Наблюдение добавлено в текущую сессию.') }
  const persist = async () => { const episode = { id: id(), createdAt: new Date().toISOString(), label: `Эпизод ${new Date().toLocaleDateString('ru-RU')}`, input }; await saveEpisode(episode); setSaved(x => [episode, ...x]); setNotice('Сохранено локально в этом браузере.') }
  const download = () => { const blob = new Blob([JSON.stringify({ schemaVersion: 1, exportedAt: new Date().toISOString(), episodes: saved }, null, 2)], { type: 'application/json' }); const a = document.createElement('a'); a.href = URL.createObjectURL(blob); a.download = 'bppv-local-backup.json'; a.click(); URL.revokeObjectURL(a.href) }
  const restore = async (file?: File) => { if (!file) return; try { const data = parseBackupText(await file.text()); await importEpisodes(data.episodes); setSaved(await listEpisodes()); setNotice('Резервная копия добавлена в локальную историю.') } catch (error) { setNotice(error instanceof Error ? error.message : 'Файл не соответствует формату резервной копии приложения.') } }
  if (!consented) return <main className="onboarding"><p className="eyebrow">Личный локальный инструмент · прототип</p><h1>Наблюдения при позиционном головокружении</h1><p>Приложение помогает записать наблюдения и понять, когда домашние действия нельзя продолжать. Оно не устанавливает диагноз и не заменяет специалиста.</p><ul><li>Только для взрослых с ранее диагностированным ДППГ.</li><li>Данные остаются в этом браузере.</li><li>При новых опасных симптомах — прекратите действия и обратитесь за помощью.</li></ul><label className="check"><input type="checkbox" checked={acknowledged} onChange={event => setAcknowledged(event.target.checked)} /> Мне 18+, я понимаю ограничение инструмента и согласен на локальное хранение.</label><button className="primary" disabled={!acknowledged} onClick={() => { localStorage.setItem('bppv-consent', 'yes'); setConsented(true) }}>Начать</button></main>
  return <main><header><div><p className="eyebrow">Личный помощник · данные только на устройстве</p><h1>Позиционное головокружение</h1></div><nav>{([['home','Главная'],['screen','Скрининг'],['record','Наблюдения'],['history','История'],['help','Справка']] as const).map(([key,label]) => <button key={key} className={tab === key ? 'nav active' : 'nav'} onClick={() => setTab(key)}>{label}</button>)}</nav></header>{notice && <p className="notice" role="status">{notice}</p>}
  {tab === 'home' && <section className="hero"><h2>Сначала — краткая проверка безопасности</h2><p>Отрицательные ответы не исключают другие причины головокружения. Не проводите пробу или манёвр без ранее показанной специалистом техники.</p><div className="actions"><button className="primary" onClick={() => setTab('screen')}>Оценить новый эпизод</button><button onClick={() => setTab('record')}>Записать наблюдения</button></div><aside><strong>Домашний Эпли:</strong> {eligibility.eligible ? 'условия допуска отмечены' : 'пока недоступен'}<br/><small>Исполняемая инструкция закрыта до клинической проверки протокола и схем.</small></aside></section>}
  {tab === 'screen' && <section><h2>Текущий скрининг</h2><p>«Не знаю» не равно «Нет» и ограничит домашнее сопровождение.</p>{questions.map(([key,label]) => <article className="question" key={key}><p>{label}</p><Choice value={input.screen[key] as Answer} onChange={v => setScreen(key, v)} /></article>)}<button className="primary" onClick={() => { setTab('record'); setNotice('Скрининг учтён. Запись доступна даже при ограничениях.') }}>Перейти к записи</button></section>}
  {tab === 'record' && <section><h2>Наблюдения и предварительная интерпретация</h2><p>Сохраняйте только то, что действительно наблюдали. Неполная запись не считается отрицательной пробой.</p><div className="two"><article><Diagram side="right"/><Diagram side="left"/><ManualObservationForm onAdd={addObservation}/></article><article className="result"><p className="eyebrow">Результат</p><h3>{assessment.safetyRoute === 'emergency' ? 'Нужна экстренная помощь' : assessment.safetyRoute === 'urgent_assessment' ? 'Нужна оценка сегодня' : assessment.pattern === 'posterior_pattern' ? 'Наблюдения похожи на заднеканальный паттерн' : 'Недостаточно данных для домашнего выбора'}</h3><p>{assessment.reasons.join(' ')}</p><details><summary>Основания и ограничения</summary><p>Правила: {assessment.matchedRuleIds.join(', ') || 'нет совпадения'}. {assessment.missingData.join(' ')}</p><p>Это предварительная интерпретация ручной записи, не диагноз.</p></details><button className="primary" onClick={persist}>Сохранить эпизод</button><button className="stop" onClick={() => { setInput(emptyInput()); setTab('screen'); setNotice('Сессия остановлена. При боли или ухудшении прекратите движения и оцените новые симптомы.') }}>Остановить: боль или ухудшение</button></article></div></section>}
  {tab === 'history' && <section><h2>Локальная история</h2><p>Данные не синхронизируются между браузерами. Экспорт JSON содержит чувствительные сведения и не шифруется.</p><div className="actions"><button onClick={download} disabled={!saved.length}>Экспорт JSON</button><label className="file">Импорт JSON<input type="file" accept="application/json" onChange={e => restore(e.target.files?.[0])}/></label><button onClick={() => window.print()}>Печать / PDF</button></div>{saved.length ? <ol>{saved.map(e => <li key={e.id}><strong>{e.label}</strong><br/><small>{new Date(e.createdAt).toLocaleString('ru-RU')} · {e.input.observations.length} записей</small></li>)}</ol> : <p className="empty">История пока пуста.</p>}</section>}
  {tab === 'help' && <section><h2>Справка и границы</h2><h3>Что доступно</h3><p>Опрос, ручная запись, сохранение, экспорт и предварительное объяснение правил. Не используются камера, облачная база, AI-диагностика, лекарства или автоматический выбор манёвра.</p><h3>Манёвры</h3><p>Эпли, Семонт, Gufoni и другие методы применяются специалистами. В этой версии пошаговый мастер Эпли не активируется, пока правила и схемы не проверит клиницист.</p><h3>Источники</h3><p>AAO-HNSF BPPV Guideline, Johns Hopkins Home Epley Maneuver, NICE NG127, Bárány Society — ограничения указаны в CLINICAL_REVIEW.md.</p></section>}
  <footer>Версия правил 1.0 · непроверенный клинический контент · при новых опасных симптомах: 112 / 103</footer></main>
}
